from fastapi import FastAPI
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.templating import Jinja2Templates
from fastapi.requests import Request
import os
import json
import zipfile
import re

from graph.workflow import workflow

app = FastAPI()

templates = Jinja2Templates(directory="templates")

WORKSPACE = "workspace"
os.makedirs(WORKSPACE, exist_ok=True)


# -----------------------------
# Extract JSON safely from LLM
# -----------------------------
def extract_json(text: str):
    """Extract JSON object from raw LLM output"""

    if not text:
        return None

    # Try direct JSON
    try:
        return json.loads(text)
    except:
        pass

    # Try ```json blocks
    match = re.search(r"```json\s*(\{.*?\})\s*```", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except:
            pass

    # Try generic { ... }
    match = re.search(r"(\{.*\})", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except:
            pass

    return None


# -----------------------------
# Homepage
# -----------------------------
@app.get("/", response_class=HTMLResponse)
def homepage(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})


# -----------------------------
# Run DevTeam AI
# -----------------------------
@app.get("/run")
def run_devteam(task: str):

    result = workflow.invoke({"task": task})

    print("\n===== RAW RESULT FROM WORKFLOW =====")
    print(result)
    print("====================================\n")

    files = []

    # Case 1: already structured
    if isinstance(result, dict) and "files" in result:
        files = result["files"]

    # Case 2: JSON inside result["code"]
    elif isinstance(result, dict) and "code" in result:
        data = extract_json(result["code"])
        if data and "files" in data:
            files = data["files"]

    # Safety fallback
    if not files:
        return {
            "task": task,
            "files": [],
            "error": "No files generated by AI"
        }

    # -----------------------------
    # Write files to workspace
    # -----------------------------
    for f in files:

        if "filename" not in f or "content" not in f:
            continue

        filepath = os.path.join(WORKSPACE, f["filename"])

        os.makedirs(os.path.dirname(filepath), exist_ok=True)

        with open(filepath, "w") as file:
            file.write(f["content"])

    return {
        "task": task,
        "files": files
    }


# -----------------------------
# Get file content
# -----------------------------
@app.get("/file")
def get_file(filename: str):

    filepath = os.path.join(WORKSPACE, filename)

    if os.path.exists(filepath):

        with open(filepath, "r") as f:
            return {"content": f.read()}

    return {"content": "File not found"}


# -----------------------------
# Download project ZIP
# -----------------------------
@app.get("/download")
def download_project():

    zip_path = "project.zip"

    with zipfile.ZipFile(zip_path, "w") as zipf:

        for root, dirs, files in os.walk(WORKSPACE):

            for file in files:

                full_path = os.path.join(root, file)

                zipf.write(
                    full_path,
                    os.path.relpath(full_path, WORKSPACE)
                )

    return FileResponse(
        zip_path,
        filename="project.zip",
        media_type="application/zip"
    )